apiVersion: v1
kind: Secret
metadata:
  name: {{ include "birthday-api.fullname" . }}-secret
  labels:
    {{- include "birthday-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "birthday-api.databaseUrl" . | quote }}
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}